name: Testing pipeline (Ubuntu)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
jobs:
  ubuntu_build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: maven
      - run: mvn clean
      - run: mvn install
      - run: mvn test